### ISSUE TITLE
Create a packages folder

### ISSUE THREAD

**Issue by neurosnap** [ryanlanciaux/workspaceExample#1]
Hey Ryan!

I saw this repo and thought I'd post how yarn workspaces are normally organized

```
root
  `- packages
    `- asciioutput
    `- coloroutput
```

packages.json:
```json
{
  "workspaces": ["./packages/*"],
}
```

**Comment by ryanlanciaux** [comment]
Hey thanks for adding this :D That's generally how I do this with lerna but will use this mindset here as well. 👍
